### ISSUE TITLE
Stuck on "Loading Vercel deployment status..."

### ISSUE THREAD

**Issue by livingstonlarus** [haydenbleasel/vercel-vscode#73]
Hello,

From the status bar I see ▲ Loading and the tooltip says "Loading Vercel deployment status..."

Access token is set. Project is correctly linked.

Any idea why it's stuck on loading?

Thanks!

**Comment by abbott** [comment]
Same here...

![Screenshot 2024-04-29 at 20 20 42](https://github.com/haydenbleasel/vercel-vscode/assets/641138/d92e562c-c121-4d7c-8be7-e890d31539a3)

**Comment by haydenbleasel** [comment]
Ok, will take a look and see if I can produce a more informative message to help debug 👍

**Comment by livingstonlarus** [comment]
Updated the Vercel for VS Code extension to v.1.0.31.

Instead of ▲ Loading I now have ▲ Error and the tooltip says "Not authorized".

I created a new token and updated my Team ID (the ID was not starting with `team_` so I got that wrong in the first place, don't know where I got that ID from).

Still ▲ Error but now tooltip says "Project not found".

Ok, again, I got that wrong. I had my project name, not ID. Which should start with `prj_`.

Works! Now I have ▲ Ready and tooltip shows "project_name (ready) 4 months ago via git".

Thanks @haydenbleasel, the new error messages did help!

I'm pretty sure I used `vercel link` initially. Maybe it failed so I tried to enter IDs manually; don't really remember.

But for good measure maybe in the [Usage doc](https://marketplace.visualstudio.com/items?itemName=HaydenBleasel.vercel-vscode&ssr=false#overview) you could detail where to find each:
- Account Settings > Tokens and create a dedicated token
- Overview > [Select your project] > Settings and scroll down to Project ID
- Overview > Settings > Team > General and scroll down to Team ID

**Comment by haydenbleasel** [comment]
@livingstonlarus Done :+1:
