### ISSUE TITLE
Monorepo support

### ISSUE THREAD

**Issue by leog** [haydenbleasel/vercel-vscode#74]
At the momento, I work in a monorepo setup, with multiple apps in the `apps` folder such as `apps/web` or `apps/app`, each of them with their `.vercel` folder containing the `projectId` which is not picked up because the extension expects a `projectId` set up in the extensions settings or a root `.vercel` folder. It would be great to be able to let the extension configure itself by using the correspondent `.vercel` folder for each file with a parent folder with that configuration, that way the extension can provide information for any number of projects contained in a single monrepo.

**Comment by haydenbleasel** [comment]
Good call, I’m currently working with turborepo and encountering the same. I’ll look into it this week, alternatively I’m keen to review a PR.
